export const demoAccounts = [
  { name: 'Minha Empresa', email: 'contato@empresa.com', color: 'blue', credits: 50 },
  { name: 'Cliente Premium', email: 'premium@cliente.com', color: 'emerald', credits: 30 },
  { name: 'Agência Digital', email: 'contato@agencia.com', color: 'rose', credits: 80 },
];

export const demoProjects = [
  {
    name: 'Central Opus Flow',
    description:
      'Landing page principal da marca. Design moderno com seções de hero, benefícios, depoimentos e CTA de conversão. Responsiva e otimizada para SEO.',
    status: 'review',
    type: 'landing',
    progress: 75,
    url: 'https://central-opus-flow.lovable.app',
    screenshot: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    is_favorite: true,
    view_count: 15,
    notes: 'Aguardando aprovação do cliente. Link de preview enviado por WhatsApp.',
  },
  {
    name: 'Campanha Black Friday',
    description:
      'Página de vendas com countdown, ofertas exclusivas e integração com gateway de pagamento. Foco em conversão rápida com escassez e urgência.',
    status: 'draft',
    type: 'landing',
    progress: 40,
    url: 'https://exemplo.com/black-friday',
    screenshot: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80',
    view_count: 8,
    notes: 'Ajustar banner principal e revisar textos de oferta antes de enviar ao cliente.',
  },
  {
    name: 'Portfolio Agência Digital',
    description:
      'Website institucional com portfólio de trabalhos, equipe, serviços oferecidos e formulário de contato. Design premium com animações suaves.',
    status: 'published',
    type: 'website',
    progress: 100,
    url: 'https://exemplo.com/portfolio',
    screenshot: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    is_favorite: true,
    view_count: 32,
    notes: 'Projeto entregue e aprovado! Cliente muito satisfeito com o resultado final. 🎉',
  },
];

export const demoIdeas = [
  {
    title: 'Novo programa de recompensas para clientes fiéis',
    description:
      'Criar um sistema de pontos e recompensas para fidelizar clientes recorrentes, oferecendo descontos progressivos e acesso antecipado a novos produtos.',
    theme: 'Aumentar a receita',
    theme_color: '#f59e0b',
    impact: 5,
    effort: 4,
    roadmap: 'next',
    progress: 35,
    position: 0,
  },
  {
    title: 'Finalização de compra expressa com 1 clique',
    description:
      'Implementar checkout simplificado que permite ao cliente finalizar a compra com apenas um clique, salvando dados de pagamento de forma segura.',
    theme: 'Conquistar clientes',
    theme_color: '#10b981',
    impact: 5,
    effort: 3,
    roadmap: 'now',
    progress: 65,
    position: 1,
  },
  {
    title: 'Melhore a experiência da lista de desejos',
    description:
      'Redesenhar a funcionalidade de wishlist com notificações de preço, compartilhamento social e sugestões inteligentes baseadas nos itens salvos.',
    theme: 'Atrair os usuários',
    theme_color: '#ef4444',
    impact: 4,
    effort: 2,
    roadmap: 'next',
    progress: 15,
    position: 2,
  },
  {
    title: 'Refatore os dados do perfil do usuário',
    description:
      'Reestruturar o módulo de perfil para incluir preferências de comunicação, histórico de interações e painel de atividade personalizado.',
    theme: 'Atrair os usuários',
    theme_color: '#ef4444',
    impact: 3,
    effort: 3,
    roadmap: 'later',
    progress: 5,
    position: 3,
  },
  {
    title: 'Explore as funções de viagem e hospedagem',
    description:
      'Pesquisar e validar a viabilidade de integrar funcionalidades de reservas e roteiros de viagem como novo vertical de negócio.',
    theme: 'Expandir horizontes',
    theme_color: '#8b5cf6',
    impact: 1,
    effort: 5,
    roadmap: 'wont',
    progress: 0,
    position: 4,
  },
];

export const scheduledMessageTemplates = [
  'Olá! Tudo bem? Passando para lembrar sobre nosso projeto. 😊',
  'Bom dia! Como estão as coisas por aí? Alguma novidade?',
  'Oi! Só confirmando nossa reunião. Pode me dar um retorno?',
  'Olá! Gostaria de saber se recebeu a proposta que enviei.',
  'Bom dia! Segue o link do material atualizado do projeto.',
  'Oi! Lembrando que o prazo de entrega está se aproximando. ⏰',
  'Olá! Já finalizei as alterações solicitadas. Pode conferir?',
  'Bom dia! Preciso de sua aprovação para seguir com a próxima etapa.',
  'Oi! Temos novidades incríveis sobre o projeto. Vamos conversar?',
  'Olá! Enviando o relatório mensal de progresso. 📊',
  'Bom dia! Confirma o horário da nossa call de amanhã?',
  'Oi! O pagamento referente ao mês anterior já está disponível?',
  'Olá! Preparei uma prévia do layout para sua análise. 🎨',
  'Bom dia! Gostaria de agendar uma reunião para esta semana.',
  'Oi! Segue a fatura atualizada conforme combinamos.',
  'Olá! Estou disponível para tirar qualquer dúvida. 💬',
  'Bom dia! Lembrete: a campanha começa na próxima segunda!',
  'Oi! Finalizei o briefing. Pode dar uma olhada quando puder?',
  'Olá! Preciso dos arquivos para dar continuidade ao trabalho.',
  'Bom dia! Tudo certo para o lançamento? Confirme por favor. 🚀',
  'Oi! Estou enviando as métricas da semana passada.',
  'Olá! Que tal agendarmos um café para alinhar os próximos passos? ☕',
  'Bom dia! Atualizei o cronograma conforme solicitado.',
  'Oi! Lembrete amigável sobre o feedback pendente.',
  'Olá! Nova versão do projeto disponível para revisão.',
  'Bom dia! Confirmando o envio do contrato para assinatura. ✍️',
  'Oi! Gostaria de apresentar uma ideia nova para o projeto.',
  'Olá! Segue o resumo da reunião de hoje.',
  'Bom dia! Última chamada para aprovação antes da entrega final.',
  'Oi! Obrigado pela parceria este mês! Até o próximo. 🤝',
];